### ISSUE TITLE
undefined method `except' after update to 5.0.10

### ISSUE THREAD

**Issue by fist28** [mhenrixon/sidekiq-unique-jobs#263]
Hi,
I updated gem from 4.0.18 to current stable (5.0.10).
After the update I got multiple errors in console/log:
```
irb(main):002:0> SomeJob.perform_async("some_string")
2018-04-27T14:12:47.034Z 1 TID-bp52d SidekiqUniqueJobs::UniqueArgs ERROR: unique_args(["some_string"]) : failed with (undefined method `except' for "some_string":String
Did you mean?  exec)
2018-04-27T14:12:47.035Z 1 TID-bp52d SidekiqUniqueJobs::UniqueArgs ERROR: undefined method `except' for "POL":String
Did you mean?  exec
```

jobs look like working correctly but something is wrong.
I use sideqkiq in 5.1.3 version without ActiveJob.
Rails 4.2.5
ruby 2.3.6

Can you help me?

**Comment by mhenrixon** [comment]
@fist28 it looks like you are using a `.unique_args` method in your worker that is using except. I just checked the code base and I don't use except anywhere in the gem code except in documentation somewhere. Did you copy from the documentation worker examples?
